### PR TITLE
Request for code Review - JavaScript Restaurant Page

### PR DESCRIPTION
**Pull request by rloterh**
- All elements and pages created using JavaScript, except  #content as instructed.
- Tab-like feature implemented.
- Webpack configured and running effectively.

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Invalid Submission 🔴 
This is an invalid submission as the linters are failing.

**Comment by rloterh** [comment]
- Linter issue fixed.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Robert Loterh** 
Good job with your first submission for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
Just one last detail to improve before you can go ahead:

- [ ] In your package.json file, add the next:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
```
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by rloterh** [comment]
- Added webpack build scripts to package.json

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- Good use of ES6+ :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] Please, make sure that you use the same linter config as the [original](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml):
- For instance, in your `.github/workflows/linters.yml` you have:
`npm install --save-dev **eslint@6.8.x** **eslint-config-airbnb-base@14.1.x** **eslint-plugin-import@2.20.x** **babel-eslint@10.1.x**`
In the original, we have:
`npm install --save-dev **eslint@7.x** **eslint-config-airbnb-base@14.x** **eslint-plugin-import@2.x** **babel-eslint@10.x**`

- [ ] It will be nice if all commands in your scripts work because when I try to use **npm start**, I got this error:


Nice to have:

- [ ] Adding external <script> tags to the < head > or to < div > of your project can slow page loads. I suggest that you put  `<script src="./main.js"></script>` just before **</body>**

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Comment by rloterh** [comment]
- Updated linters

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @rloterh**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] your scripts are not working, this is an issue with your webpack-cli package version. you have to oprions,
1: downgrade your webpack-cli version. 
2: update your scripts so that they work with the new vesion.
the updated start script: `  "start": "webpack serve --mode=development --open"`


---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by rloterh** [comment]
- Updated webpack configuration

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
